name: Trevor Greenleaf
favicon: null
layout_spectrum: 0.4771683537401259
typography_spectrum: 0.2643590352963656
title: Trevor Greenleaf
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8125
  lightness: 0.6647433214820921
  saturation: 0.2937759757041931
  rhythmicContrast: 0.7154708080925047
purpose: []
